version: '3.8'

services:
  dev:
    build: .
    image: project-name
    container_name: project-name-container
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: bash